apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-api-sa
  namespace: payment
  labels:
    app: payment-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: payment
  labels:
    app: postgres
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-report-sa
  namespace: payment
  labels:
    app: payment-service
    component: reporting
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-sa
  namespace: payment
  labels:
    app: jaeger
    component: tracing
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zipkin-sa
  namespace: payment
  labels:
    app: zipkin
    component: tracing
automountServiceAccountToken: false

